FROM golang:1.23.0-alpine AS build

WORKDIR /app

RUN apk add --no-cache gcc musl-dev
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -o /agent ./cmd/agent

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=build /agent ./agent

ENV COMPUTING_POWER=5
ENV GRPC_SERVER=orchestrator:50051
ENV CGO_ENABLED=1

CMD ["./agent"]
